#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: group_id
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#cloud:
#   aws:
#      region:
#         static: us-east-1
#         auto: false
#      stack:
#         auto: false
server:
   port: 8081

spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: messageDB